/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Banco.Acessa;
import java.awt.Color;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import telas.TrabalhaTela;

/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
    
    public Principal() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btnPrincipal.setSelected(true);
        
        new TrabalhaTela(pnlPrincipal, new telas.TelaPrincipal());
           
        pesquisaProf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        btnPrincipal = new bipbotao.BIPBotao();
        btnPesquisar = new bipbotao.BIPBotao();
        btnConsultarInsc = new bipbotao.BIPBotao();
        btnSobre = new bipbotao.BIPBotao();
        btnInserirAula = new bipbotao.BIPBotao();
        jSeparator1 = new javax.swing.JSeparator();
        btnPermissao = new bipbotao.BIPBotao();
        jPanel2 = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        tempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(239, 238, 244));
        pnlMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 0, 0, new java.awt.Color(239, 238, 244)));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlMenu.add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 110, 130));

        btnPrincipal.setForeground(new java.awt.Color(128, 128, 131));
        btnPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        btnPrincipal.setText("  Principal");
        btnPrincipal.setColorHover(new java.awt.Color(204, 204, 204));
        btnPrincipal.setColorNormal(new java.awt.Color(204, 204, 204));
        btnPrincipal.setColorPressed(new java.awt.Color(204, 204, 204));
        btnPrincipal.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnPrincipal.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnPrincipal.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnPrincipal.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrincipal.setIconTextGap(19);
        btnPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPrincipalMousePressed(evt);
            }
        });
        btnPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrincipalActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 258, 50));

        btnPesquisar.setBackground(new java.awt.Color(239, 238, 244));
        btnPesquisar.setForeground(new java.awt.Color(128, 128, 131));
        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisa.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar Professor");
        btnPesquisar.setColorHover(new java.awt.Color(204, 204, 204));
        btnPesquisar.setColorNormal(new java.awt.Color(239, 238, 244));
        btnPesquisar.setColorPressed(new java.awt.Color(204, 204, 204));
        btnPesquisar.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnPesquisar.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnPesquisar.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnPesquisar.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPesquisar.setIconTextGap(19);
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPesquisarMousePressed(evt);
            }
        });
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 50));

        btnConsultarInsc.setBackground(new java.awt.Color(239, 238, 244));
        btnConsultarInsc.setForeground(new java.awt.Color(128, 128, 131));
        btnConsultarInsc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consulta.png"))); // NOI18N
        btnConsultarInsc.setText("Consultar Inscrições");
        btnConsultarInsc.setColorHover(new java.awt.Color(204, 204, 204));
        btnConsultarInsc.setColorNormal(new java.awt.Color(239, 238, 244));
        btnConsultarInsc.setColorPressed(new java.awt.Color(204, 204, 204));
        btnConsultarInsc.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnConsultarInsc.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnConsultarInsc.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnConsultarInsc.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnConsultarInsc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConsultarInsc.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConsultarInsc.setIconTextGap(19);
        btnConsultarInsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnConsultarInscMousePressed(evt);
            }
        });
        btnConsultarInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarInscActionPerformed(evt);
            }
        });
        pnlMenu.add(btnConsultarInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 250, 50));

        btnSobre.setBackground(new java.awt.Color(239, 238, 244));
        btnSobre.setForeground(new java.awt.Color(128, 128, 131));
        btnSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sobre.png"))); // NOI18N
        btnSobre.setText("Sobre o Sistema");
        btnSobre.setColorHover(new java.awt.Color(204, 204, 204));
        btnSobre.setColorNormal(new java.awt.Color(239, 238, 244));
        btnSobre.setColorPressed(new java.awt.Color(204, 204, 204));
        btnSobre.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnSobre.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnSobre.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnSobre.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnSobre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSobre.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSobre.setIconTextGap(19);
        btnSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSobreMousePressed(evt);
            }
        });
        btnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSobreActionPerformed(evt);
            }
        });
        pnlMenu.add(btnSobre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 50));

        btnInserirAula.setBackground(new java.awt.Color(239, 238, 244));
        btnInserirAula.setForeground(new java.awt.Color(128, 128, 131));
        btnInserirAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inserir.png"))); // NOI18N
        btnInserirAula.setText("  Inserir Aula");
        btnInserirAula.setColorHover(new java.awt.Color(204, 204, 204));
        btnInserirAula.setColorNormal(new java.awt.Color(239, 238, 244));
        btnInserirAula.setColorPressed(new java.awt.Color(204, 204, 204));
        btnInserirAula.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnInserirAula.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnInserirAula.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnInserirAula.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnInserirAula.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInserirAula.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInserirAula.setIconTextGap(19);
        btnInserirAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnInserirAulaMousePressed(evt);
            }
        });
        btnInserirAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirAulaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnInserirAula, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 258, 50));
        pnlMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 260, 10));

        btnPermissao.setBackground(new java.awt.Color(239, 238, 244));
        btnPermissao.setForeground(new java.awt.Color(128, 128, 131));
        btnPermissao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/permissao.png"))); // NOI18N
        btnPermissao.setText("Adicionar/remover  Gestor");
        btnPermissao.setColorHover(new java.awt.Color(204, 204, 204));
        btnPermissao.setColorNormal(new java.awt.Color(239, 238, 244));
        btnPermissao.setColorPressed(new java.awt.Color(204, 204, 204));
        btnPermissao.setColorTextHover(new java.awt.Color(128, 128, 131));
        btnPermissao.setColorTextNormal(new java.awt.Color(128, 128, 131));
        btnPermissao.setColorTextPressed(new java.awt.Color(128, 128, 131));
        btnPermissao.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnPermissao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPermissao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPermissao.setIconTextGap(19);
        btnPermissao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPermissaoMousePressed(evt);
            }
        });
        btnPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermissaoActionPerformed(evt);
            }
        });
        pnlMenu.add(btnPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 250, 50));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setBackground(new java.awt.Color(255, 255, 255));
        lblNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 600, 41));

        tempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tempo.setForeground(new java.awt.Color(255, 255, 255));
        tempo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(tempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 180, 30));

        jButton1.setBackground(new java.awt.Color(128, 128, 131));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/saida.png"))); // NOI18N
        jButton1.setToolTipText("Sair do Sistema");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 40, 30));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mover = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mover.x - x, mover.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrincipalActionPerformed
        new TrabalhaTela(pnlPrincipal, new telas.TelaPrincipal());
        if(this.btnPrincipal.isSelected()){
            this.btnPrincipal.setColorNormal(new Color(204,204,204));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));
            
            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

        }else{
            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));
        }    
        
    }//GEN-LAST:event_btnPrincipalActionPerformed

    private void btnPrincipalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrincipalMousePressed
        this.btnPrincipal.setSelected(true);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(false);
        this.btnPesquisar.setSelected(false);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnPrincipalMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     MudaImagem("/img/logobib_des.png");
     relogio();


    }//GEN-LAST:event_formWindowOpened

    private void btnInserirAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirAulaActionPerformed
        new TrabalhaTela(pnlPrincipal, new telas.TelaInserirAula());
        if(this.btnInserirAula.isSelected()){
            this.btnInserirAula.setColorNormal(new Color(204,204,204));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
            
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

           
        }else{
            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnInserirAulaActionPerformed

    private void btnInserirAulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirAulaMousePressed
       this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(true);
        this.btnConsultarInsc.setSelected(false);
        this.btnPesquisar.setSelected(false);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(false);
       
    }//GEN-LAST:event_btnInserirAulaMousePressed

    private void btnConsultarInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarInscActionPerformed
        new TrabalhaTela(pnlPrincipal, new telas.TelaConsultar());
        if(this.btnConsultarInsc.isSelected()){
            this.btnConsultarInsc.setColorNormal(new Color(204,204,204));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
            
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

         
            
        }else{
            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnConsultarInscActionPerformed

    private void btnConsultarInscMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultarInscMousePressed
       this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(true);
        this.btnPesquisar.setSelected(false);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(false);
       
    }//GEN-LAST:event_btnConsultarInscMousePressed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       new TrabalhaTela(pnlPrincipal, new telas.TelaPesquisaProfessor());
        if(this.btnPesquisar.isSelected()){
            this.btnPesquisar.setColorNormal(new Color(204,204,204));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));
            
            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));
            
            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
            
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

        }else{
            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMousePressed
        this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(false);
        this.btnPesquisar.setSelected(true);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(false);
       
    }//GEN-LAST:event_btnPesquisarMousePressed

    private void btnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSobreActionPerformed
        new TrabalhaTela(pnlPrincipal, new telas.TelaSobre());
        if(this.btnSobre.isSelected()){
            this.btnSobre.setColorNormal(new Color(204,204,204));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
            
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

        }else{
            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnSobreActionPerformed

    private void btnSobreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSobreMousePressed
        this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(false);
        this.btnPesquisar.setSelected(false);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(true);
    }//GEN-LAST:event_btnSobreMousePressed

    private void btnPermissaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPermissaoMousePressed
        this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(false);
        this.btnPermissao.setSelected(true);
        this.btnPesquisar.setSelected(false);
        this.btnSobre.setSelected(false);
    }//GEN-LAST:event_btnPermissaoMousePressed

    private void btnPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermissaoActionPerformed
       new TrabalhaTela(pnlPrincipal, new telas.TelaPermissao());
        if(this.btnPermissao.isSelected()){
            this.btnPermissao.setColorNormal(new Color(204,204,204));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));
            
            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));

         
            
        }else{
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));
        }
    }//GEN-LAST:event_btnPermissaoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bipbotao.BIPBotao btnConsultarInsc;
    private bipbotao.BIPBotao btnInserirAula;
    private bipbotao.BIPBotao btnPermissao;
    private bipbotao.BIPBotao btnPesquisar;
    public static bipbotao.BIPBotao btnPrincipal;
    public static bipbotao.BIPBotao btnSobre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLogo;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel pnlCentro;
    public static javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JLabel tempo;
    // End of variables declaration//GEN-END:variables

    public void MudaImagem(String end) {

        Image troca = Toolkit.getDefaultToolkit().getImage(getClass().getResource(end));

        ImageIcon icone = new ImageIcon(troca);

        icone.setImage(troca.getScaledInstance(jLogo.getWidth(), jLogo.getHeight(), Image.SCALE_FAST));

        jLogo.setIcon(icone);

    }

    int i = 0;
    SimpleDateFormat formatador;
    String Data;

    public void relogio() {
        Locale locale = new Locale("pt", "BR"); // Localidade

        // Criando o calendário e ajustando para 00:00:00
        GregorianCalendar calendar = new GregorianCalendar();
        calendar.set(GregorianCalendar.HOUR_OF_DAY, 0);
        calendar.set(GregorianCalendar.MINUTE, 0);
        calendar.set(GregorianCalendar.SECOND, 0);

        // Formatando a hora
        SimpleDateFormat formatador = new SimpleDateFormat("HH':'mm':'ss", locale);
        String Data = formatador.format(calendar.getTime());

        timer.start();
    
}

//Método thread
    private javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {

        public void actionPerformed(java.awt.event.ActionEvent e) {

            segundos++;
                if (segundos == 60) {
                    segundos = 0;
                    minutos++;
                }
                if (minutos == 60) {
                    minutos = 0;
                    horas++;
                }

                // Atualiza o texto do relógio
                String data = String.format("%02d:%02d:%02d", horas, minutos, segundos);
                tempo.setText(data);

        }

    });
        
        
    public void recuar(){
        int posicao = pnlMenu.getX();
        if(posicao > -1){
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }
    
     int horas = 0;
     int minutos = 0;
     int segundos = 0;

     
     static String cpfTopo;

     
     Acessa objA = new Acessa();
    
    public void pesquisaProf() {
        try {
            objA.entBanco();
            
            objA.RS = objA.stmt.executeQuery("SELECT * FROM professor  where cpf='" + cpfTopo + "'");

            if (objA.RS.next()) {
                lblNome.setText(objA.RS.getString("nome_prof"));
                Banco.dados_pesquisa.unidade = objA.RS.getInt("gestorUe");
            }
        } catch (Exception e) {

        }

    }
    
    
    public void voltarTelaPrincipal(){
        
        new TrabalhaTela(pnlPrincipal, new telas.TelaSobre());
        if(this.btnSobre.isSelected()){
            this.btnSobre.setColorNormal(new Color(204,204,204));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
            
            this.btnPermissao.setColorNormal(new Color(239,238,244));
            this.btnPermissao.setColorHover(new Color(204,204,204));
            this.btnPermissao.setColorPressed(new Color(204,204,204));

            this.btnInserirAula.setColorNormal(new Color(239,238,244));
            this.btnInserirAula.setColorHover(new Color(204,204,204));
            this.btnInserirAula.setColorPressed(new Color(204,204,204));

            this.btnConsultarInsc.setColorNormal(new Color(239,238,244));
            this.btnConsultarInsc.setColorHover(new Color(204,204,204));
            this.btnConsultarInsc.setColorPressed(new Color(204,204,204));

            this.btnPesquisar.setColorNormal(new Color(239,238,244));
            this.btnPesquisar.setColorHover(new Color(204,204,204));
            this.btnPesquisar.setColorPressed(new Color(204,204,204));

            this.btnPrincipal.setColorNormal(new Color(239,238,244));
            this.btnPrincipal.setColorHover(new Color(204,204,204));
            this.btnPrincipal.setColorPressed(new Color(204,204,204));

        }else{
            this.btnSobre.setColorNormal(new Color(239,238,244));
            this.btnSobre.setColorHover(new Color(204,204,204));
            this.btnSobre.setColorPressed(new Color(204,204,204));
        }
        
    }
    
    public void liberarBotao(){
        
        this.btnPrincipal.setSelected(false);
        this.btnInserirAula.setSelected(false);
        this.btnConsultarInsc.setSelected(false);
        this.btnPesquisar.setSelected(false);
        this.btnPermissao.setSelected(false);
        this.btnSobre.setSelected(true);
        
    } 
     
}
