/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Banco.Acessa;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RojeruSan
 */
public class TelaConsultar extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public TelaConsultar() {
        initComponents();
        pesquisaMateria();
        cbxDisciplinaC1.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaC = new javax.swing.JTable();
        cbxCursoC = new javax.swing.JComboBox<>();
        telProf = new javax.swing.JLabel();
        emailProf = new javax.swing.JLabel();
        cbxDisciplinaC1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(244, 244, 244));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaC.setFont(new java.awt.Font("Bernard MT Condensed", 0, 15)); // NOI18N
        tabelaC.setForeground(new java.awt.Color(150, 150, 150));
        tabelaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Disciplina", "Pontuação", "Colocação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaC);
        if (tabelaC.getColumnModel().getColumnCount() > 0) {
            tabelaC.getColumnModel().getColumn(0).setMinWidth(220);
            tabelaC.getColumnModel().getColumn(0).setPreferredWidth(220);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 610, 380));

        cbxCursoC.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        cbxCursoC.setForeground(new java.awt.Color(150, 150, 150));
        cbxCursoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o Curso" }));
        cbxCursoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursoCActionPerformed(evt);
            }
        });
        add(cbxCursoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 230, -1));

        telProf.setFont(new java.awt.Font("Bernard MT Condensed", 0, 20)); // NOI18N
        telProf.setForeground(new java.awt.Color(150, 150, 150));
        telProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/telefone.png"))); // NOI18N
        telProf.setText("Telefone:");
        add(telProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 260, 50));

        emailProf.setFont(new java.awt.Font("Bernard MT Condensed", 0, 20)); // NOI18N
        emailProf.setForeground(new java.awt.Color(150, 150, 150));
        emailProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/email.png"))); // NOI18N
        emailProf.setText("Email:");
        add(emailProf, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 490, 310, 50));

        cbxDisciplinaC1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 16)); // NOI18N
        cbxDisciplinaC1.setForeground(new java.awt.Color(150, 150, 150));
        cbxDisciplinaC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha a Disciplina" }));
        cbxDisciplinaC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxDisciplinaC1MouseClicked(evt);
            }
        });
        cbxDisciplinaC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDisciplinaC1ActionPerformed(evt);
            }
        });
        add(cbxDisciplinaC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
           
    }//GEN-LAST:event_formFocusGained

    private void cbxCursoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoCActionPerformed
        int posicao = cbxCursoC.getSelectedIndex();
        if (posicao > 0){
            nomeCursoC = cbxCursoC.getSelectedItem().toString();
            pesquisaDisc();
            cbxDisciplinaC1.setEnabled(true);
           
        }

//ORDER BY total_sales_value DESC;
    }//GEN-LAST:event_cbxCursoCActionPerformed

    private void cbxDisciplinaC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDisciplinaC1ActionPerformed
       
            int posicao = cbxDisciplinaC1.getSelectedIndex();
        if (posicao > 0) {
            String dados = cbxDisciplinaC1.getSelectedItem().toString();
            String[] saida = cbxDisciplinaC1.getSelectedItem().toString().split(" ");
            nomeDisciplina = saida[0];
            id_disc = Integer.parseInt(saida[5]);
            pesquisaTabela();
        }
        

    }//GEN-LAST:event_cbxDisciplinaC1ActionPerformed

    private void cbxDisciplinaC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxDisciplinaC1MouseClicked

    }//GEN-LAST:event_cbxDisciplinaC1MouseClicked

    private void tabelaCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCMouseClicked
        
        pesquisaProf((String) tabelaC.getValueAt(0, 0), Integer.parseInt((String) tabelaC.getValueAt(0, 2)));
        //tabelaC.getSelectedRow() pegar linha
    }//GEN-LAST:event_tabelaCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxCursoC;
    private javax.swing.JComboBox<String> cbxDisciplinaC1;
    private javax.swing.JLabel emailProf;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaC;
    private javax.swing.JLabel telProf;
    // End of variables declaration//GEN-END:variables

Acessa objA = new Acessa();

String nomeCursoC, nomeDisciplina;
int id_disc;

DefaultTableModel tableModel;

public void pesquisaMateria() {
        objA.entBanco();
        try {         
            objA.RS = objA.stmt.executeQuery("SELECT DISTINCT  nome_curso FROM aulas_disponiveis  where unidade="+Banco.dados_pesquisa.unidade+" order by nome_curso");
            while (objA.RS.next()) {
                cbxCursoC.addItem(objA.RS.getString("nome_curso"));
            }
        } catch (Exception e) {
        }
    }

public void pesquisaDisc() {
        objA.entBanco();
        try {
            tableModel = (DefaultTableModel) tabelaC. getModel();
            tableModel.setNumRows(0);
            
            objA.RS = objA.stmt.executeQuery("SELECT DISTINCT id, nome_disciplina, horario_aula FROM aulas_disponiveis  where unidade="+Banco.dados_pesquisa.unidade+"  and  nome_curso = '"+nomeCursoC+"' order by nome_disciplina");
            cbxDisciplinaC1.removeAllItems();
            cbxDisciplinaC1.addItem("Escolha a Disciplina");
            while (objA.RS.next()) {
                cbxDisciplinaC1.addItem(objA.RS.getString("nome_disciplina")+" - "+objA.RS.getString("horario_aula") + " - " +objA.RS.getInt("id"));
            }

        } catch (Exception e) {
        }
    }

public void pesquisaTabela() {
        objA.entBanco();
        try {
            objA.RS = objA.stmt.executeQuery("SELECT professor.nome_prof, aula_ampliacao.nome_disciplina, professor.pontos_prof FROM professor JOIN  aula_ampliacao ON  professor.CPF = aula_ampliacao.CPF LEFT JOIN aulas_disponiveis ON aulas_disponiveis.id = "+id_disc+" WHERE aula_ampliacao.unidade = "+Banco.dados_pesquisa.unidade+" and aula_ampliacao.nome_disciplina='"+nomeDisciplina+"' and aula_ampliacao.nome_curso = '"+nomeCursoC+"' and aula_ampliacao.id_disponiveis = "+id_disc+"ORDER BY professor.pontos_prof DESC");
            
            tableModel = (DefaultTableModel) tabelaC. getModel();
            tableModel.setNumRows(0);
            int i=0;
            
            while (objA.RS.next()) {
                ((DefaultTableModel) tabelaC.getModel()). addRow(new Vector());

                tabelaC.getModel().setValueAt(objA.RS.getString("nome_prof"), i, 0);
                //tabelaC é o nome da tabela
                tabelaC.getModel().setValueAt(objA.RS.getString("nome_disciplina"), i, 1);
                tabelaC.getModel().setValueAt(objA.RS.getString("pontos_prof"), i, 2);
                tabelaC.getModel().setValueAt(i+1, i, 3);
                i++;
            }

          
        } catch (Exception e) {
        }
    }

public void pesquisaProf(String nomeP, int pontosP) {
        objA.entBanco();
        try {
            objA.RS = objA.stmt.executeQuery("SELECT telProf, emailProf FROM professor  where nome_prof = '"+nomeP+"' and pontos_prof="+pontosP+"");
            
            if (objA.RS.next()) {
                telProf.setText(objA.RS.getString("telProf"));
                emailProf.setText(objA.RS.getString("emailProf"));
            }

        } catch (Exception e) {
        }
    }


}
