/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import principal.Principal;

/**
 *
 * @author RojeruSan
 */
public class TelaSobre extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public TelaSobre() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logobib_des.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 500, -1));

        jScrollPane1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("O Sistema Busca Inteligente de Professores (BIP) são\npartes para integração e inovação do software de RH do\nCPS, foi elaborado como parte do Plano de Mestrado \nProfissional em Formação de Gestores Educacionais \nda UNICID, ele segue os princípios da Licença Pública \nGeral GNU versão 2 com exceção do Classpath. \nFoi Desenvolvido por Alcimar Barbosa dos Reis \ncom a orientação do \nProfessor Doutor Rodnei Pereira.");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 530, 190));

        jButton1.setFont(new java.awt.Font("Bernard MT Condensed", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(128, 128, 131));
        jButton1.setText("Sair");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Principal.btnPrincipal.doClick();
       
        Principal.btnSobre.setColorNormal(new Color(239,238,244));
        Principal.btnSobre.setColorHover(new Color(204,204,204));
        Principal.btnSobre.setColorPressed(new Color(204,204,204));
        Principal.btnPrincipal.setColorNormal(new Color(204,204,204));
        Principal.btnPrincipal.setColorHover(new Color(204,204,204));
        Principal.btnPrincipal.setColorPressed(new Color(204,204,204));
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed

    }//GEN-LAST:event_jButton1MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
