/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import Banco.Acessa;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author RojeruSan
 */
public class TelaPermissao extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    public TelaPermissao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ctUsuarioP = new javax.swing.JTextField();
        imagemPermissao = new javax.swing.JLabel();
        btnRetirar = new javax.swing.JButton();
        btnAcresc = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 244, 244));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(128, 128, 131));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/web.png"))); // NOI18N
        jLabel7.setText("Permissão");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 440, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consulta.png"))); // NOI18N
        jLabel1.setToolTipText("Clique para fazer a busca");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 50, 50));

        ctUsuarioP.setBackground(new java.awt.Color(240, 240, 240));
        ctUsuarioP.setFont(new java.awt.Font("Bernard MT Condensed", 0, 20)); // NOI18N
        ctUsuarioP.setForeground(new java.awt.Color(128, 128, 131));
        ctUsuarioP.setText("Entre  com o usuario");
        ctUsuarioP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ctUsuarioPFocusGained(evt);
            }
        });
        ctUsuarioP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctUsuarioPActionPerformed(evt);
            }
        });
        add(ctUsuarioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 380, 50));

        imagemPermissao.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(imagemPermissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 130, 160));

        btnRetirar.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnRetirar.setForeground(new java.awt.Color(128, 128, 131));
        btnRetirar.setText("<html><head><body><center>Retirar<br>Permissão");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 400, 120, -1));

        btnAcresc.setFont(new java.awt.Font("Bernard MT Condensed", 0, 18)); // NOI18N
        btnAcresc.setForeground(new java.awt.Color(128, 128, 131));
        btnAcresc.setText("<html><head><body><center>Acrescentar<br>Permissão");
        btnAcresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcrescActionPerformed(evt);
            }
        });
        add(btnAcresc, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 400, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ctUsuarioPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctUsuarioPActionPerformed
        pesquisa();
    }//GEN-LAST:event_ctUsuarioPActionPerformed

    private void ctUsuarioPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ctUsuarioPFocusGained
       ctUsuarioP.setText("");
       ctUsuarioP.requestFocus();
    }//GEN-LAST:event_ctUsuarioPFocusGained

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        pesquisa();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnAcrescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcrescActionPerformed
       try {
            int registro;
            registro = objA.stmt.executeUpdate ("update professor set gestorUe ="+Banco.dados_pesquisa.unidade+" where  cpf ='"+usu+"'");
            objA.stmt.executeUpdate ("update login set statusLog='a' where  usuario='"+login+"'");
            if (registro !=0){
                JOptionPane.showMessageDialog(this, "Permissão concedida");
                limpar();
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex);
        }

    }//GEN-LAST:event_btnAcrescActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        try {
            int registro;
            registro = objA.stmt.executeUpdate ("update professor set gestorUe =0 where  cpf ='"+usu+"'");
            objA.stmt.executeUpdate ("update login set statusLog='p' where  usuario='"+login+"'");
            if (registro !=0){
                JOptionPane.showMessageDialog(this, "Permissão retirada");
                limpar();
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro: " + ex);
        }

    }//GEN-LAST:event_btnRetirarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcresc;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JTextField ctUsuarioP;
    private javax.swing.JLabel imagemPermissao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    
    Acessa objA = new Acessa();
    byte[] imgBytes;
    String usu, login="";
    
    public void pesquisa() {
        if (!ctUsuarioP.getText().isEmpty()) {
            try {
                objA.entBanco();
                login = ctUsuarioP.getText();
                objA.RS = objA.stmt.executeQuery("SELECT * FROM login  where usuario='" + login + "'");
                
                if (objA.RS.next()){
                    usu = objA.RS.getString("cpf");
                    imgBytes = objA.RS.getBytes("imagem_bd");
                    MudaImagem(imgBytes);
                    
                }
                
            } catch (Exception e) {

            }
        } else {
            JOptionPane.showMessageDialog(this, "Preencha o campo com\no usuário do professor", "Aviso!!", 2);
        }
    }
        
        public void MudaImagem(byte[] img) {

        Image troca = new ImageIcon(img).getImage();;

        ImageIcon icone = new ImageIcon(troca);

        icone.setImage(troca.getScaledInstance(imagemPermissao.getWidth(), imagemPermissao.getHeight(), Image.SCALE_FAST));

        imagemPermissao.setIcon(icone);

    }
        public void limpar(){
            ctUsuarioP.setText("Entre  com o usuario");
            imagemPermissao.setIcon(null);
        }



}
